[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "potterlang"
version = "0.1.2"
description = "An esoteric, wizarding-themed interpreted programming language."
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Jaspreet Singh" }]

[project.scripts]
potter = "potterlang.potter:main"